receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  otlp:
    endpoint: "tempo-prod-19-prod-ap-south-1.grafana.net:443"
    headers:
      Authorization: "Basic OTU1NDU2OmdsY19leUp2SWpvaU1URTRPRGc0TkNJc0ltNGlPaUp6ZEdGamF5MHhNREF6TXpZeExXaDBMWEpsWVdRdGRHVnRjQzFyWlhraUxDSnJJam9pT0hsQ1ZUZExNemt6Y2pKWVV6ZFpNemN6UVdsYVRtSkdJaXdpYlNJNmV5SnlJam9pY0hKdlpDMWhjQzF6YjNWMGFDMHhJbjE5"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]