name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Export Workflow Trace
      uses: inception-health/otel-export-trace-action@latest
      with:
        otlpEndpoint: 'https://caaa-2401-4900-1c3c-34d8-570-7dc3-950e-3de8.ngrok-free.app'
        otlpHeaders: 'Content-Type=application/json'
        githubToken: ${{ secrets.GITHUB_TOKEN }}